default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  host: Rails.application.credentials.db[:host]
  port: Rails.application.credentials.db[:port]
  encoding: utf8
  database: Rails.application.credentials.db[:database]
  username: Rails.application.credentials.db[:user]
  password: Rails.application.credentials.db[:password]
  pool: 5
  timeout: 5000